version: '3'

services:
  nats:
    image: 'nats:1.4.1'
    container_name: "polystack-nats"
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  polystack-endpoint:
    build: "./endpoint"
    container_name: "polystack-endpoint"
    stdin_open: true
    links:
      - nats
    environment:
      - "BUFFER_SIZE=64"
      - "LOG_ERRORS=true"
      - "NATS_URI=nats://nats:4222"
      - "REQ_SUBJECT=endpoint-computation-requests"
      - "RES_SUBJECT=endpoint-computation-responses"
    depends_on:
      - nats
      - polystack-middleware
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  polystack-middleware:
    build: "./middleware"
    container_name: "polystack-middleware"
    links:
      - nats
    environment:
      - "APP_ID=middleware"
      - "LOG_PATH=./logs/middleware.log"
      - "NATS_URI=nats://nats:4222"
      - "REQ_WORKER=worker-computation-requests"
      - "RES_WORKER=worker-computation-responses"
      - "REQ_ENDPOINT=endpoint-computation-requests"
      - "RES_ENDPOINT=endpoint-computation-responses"
    depends_on:
      - nats
    volumes:
      - "./logs:/usr/src/app/logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  polystack-worker:
    build: "./worker"
    container_name: "polystack-worker"
    links:
      - nats
    environment:
      - "APP_ID=worker"
      - "NATS_URI=nats://nats:4222"
      - "SUB_SUBJECT=worker-computation-requests"
      - "PUB_SUBJECT=worker-computation-responses"
    depends_on:
      - nats
      - polystack-middleware
    volumes:
      - "./logs:/usr/src/polystack-worker/logs"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
